"""add_user_action_logs_table

Revision ID: 3d45c21f4062
Revises: a5820cd23501
Create Date: 2025-12-12 12:20:00.322584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d45c21f4062'
down_revision: Union[str, None] = 'a5820cd23501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_action_logs_action_type'), 'user_action_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_user_action_logs_created_at'), 'user_action_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_action_logs_id'), 'user_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_action_logs_user_id'), 'user_action_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_action_logs_user_id'), table_name='user_action_logs')
    op.drop_index(op.f('ix_user_action_logs_id'), table_name='user_action_logs')
    op.drop_index(op.f('ix_user_action_logs_created_at'), table_name='user_action_logs')
    op.drop_index(op.f('ix_user_action_logs_action_type'), table_name='user_action_logs')
    op.drop_table('user_action_logs')
    # ### end Alembic commands ###
