"""add_anonymous_checks

Revision ID: cc4946fa759f
Revises: 1a4188620da0
Create Date: 2026-01-31 10:22:02.695090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4946fa759f'
down_revision: Union[str, None] = '1a4188620da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_checks',
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('check_date', sa.DateTime(), nullable=False),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ip_address', 'check_date')
    )
    op.drop_constraint(op.f('check_results_document_id_fkey'), 'check_results', type_='foreignkey')
    op.create_foreign_key(None, 'check_results', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_action_logs_user_id_fkey'), 'user_action_logs', type_='foreignkey')
    op.create_foreign_key(None, 'user_action_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_action_logs', type_='foreignkey')
    op.create_foreign_key(op.f('user_action_logs_user_id_fkey'), 'user_action_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'check_results', type_='foreignkey')
    op.create_foreign_key(op.f('check_results_document_id_fkey'), 'check_results', 'documents', ['document_id'], ['id'])
    op.drop_table('anonymous_checks')
    # ### end Alembic commands ###
